version: "3"
services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
